opensea_tags = ['primary_asset_contracts', 'banner_image_url', 'chat_url',
                'created_date', 'default_to_fiat', 'description',
                'dev_buyer_fee_basis_points', 'dev_seller_fee_basis_points',
                'discord_url', 'external_url', 'featured', 'featured_image_url',
                'hidden', 'safelist_request_status', 'image_url',
                'is_subject_to_whitelist', 'large_image_url', 'medium_username',
                'name', 'only_proxied_transfers', 'opensea_buyer_fee_basis_points',
                'opensea_seller_fee_basis_points', 'payout_address',
                'require_email', 'short_description', 'slug', 'telegram_url',
                'twitter_username', 'instagram_username', 'wiki_url', 'is_nsfw',
                'owned_asset_count', 'stats.one_day_volume',
                'stats.one_day_change', 'stats.one_day_sales',
                'stats.one_day_average_price', 'stats.seven_day_volume',
                'stats.seven_day_change', 'stats.seven_day_sales',
                'stats.seven_day_average_price', 'stats.thirty_day_volume',
                'stats.thirty_day_change', 'stats.thirty_day_sales',
                'stats.thirty_day_average_price', 'stats.total_volume',
                'stats.total_sales', 'stats.total_supply', 'stats.count',
                'stats.num_owners', 'stats.average_price', 'stats.num_reports',
                'stats.market_cap', 'stats.floor_price',
                'display_data.card_display_style', 'display_data.images',
                'traits.agility.min', 'traits.agility.max',
                'traits.building_tiles.min', 'traits.building_tiles.max',
                'traits.charisma.min', 'traits.charisma.max',
                'traits.endurance.min', 'traits.endurance.max',
                'traits.intelligence.min', 'traits.intelligence.max',
                'traits.level.min', 'traits.level.max', 'traits.luck.min',
                'traits.luck.max', 'traits.resources.min', 'traits.resources.max',
                'traits.size.min', 'traits.size.max', 'traits.strength.min',
                'traits.strength.max', 'traits.total_tiles.min',
                'traits.total_tiles.max', 'traits.base_nug_scale.min',
                'traits.base_nug_scale.max', 'traits.berry_drop.min',
                'traits.berry_drop.max', 'traits.cbd.min', 'traits.cbd.max',
                'traits.flower_drop.min', 'traits.flower_drop.max',
                'traits.growth_speed.min', 'traits.growth_speed.max',
                'traits.harvest_size.min', 'traits.harvest_size.max',
                'traits.harvest_spread.min', 'traits.harvest_spread.max',
                'traits.height.min', 'traits.height.max',
                'traits.main_leaf_scale.min', 'traits.main_leaf_scale.max',
                'traits.mutability.min', 'traits.mutability.max',
                'traits.nug_drop.min', 'traits.nug_drop.max',
                'traits.nug_leaf_scale.min', 'traits.nug_leaf_scale.max',
                'traits.parent_one_id.min', 'traits.parent_one_id.max',
                'traits.parent_two_id.min', 'traits.parent_two_id.max',
                'traits.rarity.min', 'traits.rarity.max', 'traits.seed_drop.min',
                'traits.seed_drop.max', 'traits.smell_primary_strength.min',
                'traits.smell_primary_strength.max',
                'traits.smell_secondary_strength.min',
                'traits.smell_secondary_strength.max', 'traits.stem_scale.min',
                'traits.stem_scale.max', 'traits.thc.min', 'traits.thc.max']

erc20_tags = ['token_address', 'name', 'symbol', 'logo', 'thumbnail', 'decimals', 'balance']

nft_transfer_tags = ['block_number', 'block_timestamp', 'block_hash', 'transaction_hash',
                     'transaction_index', 'log_index', 'value', 'contract_type',
                     'transaction_type', 'token_address', 'token_id', 'from_address',
                     'to_address', 'amount', 'verified', 'operator']

nft_id_tags = ['token_address', 'token_id', 'contract_type', 'owner_of', 'block_number', 'block_number_minted',
               'token_uri', 'metadata', 'synced_at', 'amount', 'name', 'symbol']
